services:
  web:
    image: son29032001/novel-fe:${ENV:-dev}
    container_name: web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV:-dev}
