services:
  web:
    image: son29032001/novel-fe
    container_name: web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

  dev:
    image: son29032001/novel-fe:dev
    container_name: web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.development
